dictio = {
		"verbs" :
				 [
						 {"number":0,"description":"NOT IN USE","notes":""},
						 {"number":1,"description":"DISPLAY OCTAL COMP 1 IN R1","notes":""},
						 {"number":2,"description":"DISPLAY OCTAL COMP 2 IN R1","notes":""},
						 {"number":3,"description":"DISPLAY OCTAL COMP 3 IN R1","notes":""},
						 {"number":4,"description":"DISPLAY OCTAL COMP 1,2 IN R1,R2","notes":""},
						 {"number":5,"description":"DISPLAY OCTAL COMP 1,2,3 IN R1,R2,R3","notes":""},
						 {"number":6,"description":"DISPLAY DECIMAL IN R1 OR R1,R2 OR R1,R2,R3","notes":""},
						 {"number":7,"description":"DISPLAY DP DECIMAL IN R1,R2 (TEST ONLY)","notes":""},
						 {"number":8,"description":"","notes":""},
						 {"number":9,"description":"","notes":""},
						 {"number":10,"description":"","notes":""},
						 {"number":11,"description":"MONITOR OCTAL COMP 1 IN R1","notes":""},
						 {"number":12,"description":"MONITOR OCTAL COMP 2 IN R1","notes":""},
						 {"number":13,"description":"MONITOR OCTAL COMP 3 IN R1","notes":""},
						 {"number":14,"description":"MONITOR OCTAL COMP 1,2 IN R1,R2","notes":""},
						 {"number":15,"description":"MONITOR OCTAL COMP 1,2,3 IN R1,R2,R3","notes":""},
						 {"number":16,"description":"MONITOR DECIMAL IN R1 OR R1,R2 OR R1,R2,R3","notes":""},
						 {"number":17,"description":"MONITOR DP DECIMAL IN R1,R2 (TEST ONLY) ","notes":""},
						 {"number":18,"description":"","notes":""},
						 {"number":19,"description":"","notes":""},
						 {"number":20,"description":"","notes":""},
						 {"number":21,"description":"LOAD COMPONENT 1 INTO R1","notes":""},
						 {"number":22,"description":"LOAD COMPONENT 2 INTO R2","notes":""},
						 {"number":23,"description":"LOAD COMPONENT 3 INTO R3","notes":""},
						 {"number":24,"description":"LOAD COMPONENT 1,2, INTO R1,R2","notes":""},
						 {"number":25,"description":"LOAD COMPONENT 1,2,3 INTO R1,R2,R3","notes":""},
						 {"number":26,"description":"","notes":""},
						 {"number":27,"description":"DISPLAY FIXED MEMORY","notes":""},
						 {"number":28,"description":"","notes":""},
						 {"number":29,"description":"","notes":""},
						 {"number":30,"description":"REQUEST EXECUTIVE","notes":""},
						 {"number":31,"description":"REQUEST WAITLIST000258,000192:												 ","notes":""},
						 {"number":32,"description":"RECYCLE PROGRAM","notes":""},
						 {"number":33,"description":"PROCEED WITHOUT DSKY INPUTS","notes":""},
						 {"number":34,"description":"TERMINATE FUNCTION","notes":""},
						 {"number":35,"description":"TEST LIGHTS","notes":""},
						 {"number":36,"description":"REQUEST FRESH START","notes":""},
						 {"number":37,"description":"CHANGE PROGRAM (MAJOR MODE)","notes":""},
						 {"number":38,"description":"","notes":""},
						 {"number":39,"description":"","notes":""},
						 {"number":40,"description":"XERO CDU'S","notes":""},
						 {"number":41,"description":"COARSE ALIGN CDU'S","notes":""},
						 {"number":42,"description":"FINE ALIGN IMU","notes":""},
						 {"number":43,"description":"LOAD IMU ATT ERROR METERS","notes":""},
						 {"number":44,"description":"TERMINATE RR CONTINUOUS DESIGNATE (V41N72 OPTION 2)","notes":""},
						 {"number":45,"description":"","notes":""},
						 {"number":46,"description":"","notes":""},
						 {"number":47,"description":"INITIALIZE AGS (R47)","notes":""},
						 {"number":48,"description":"REQUEST DAP DATA LOAD ROUTINE (R03)","notes":""},
						 {"number":49,"description":"REQUEST CREW DEFINED MANEUVER ROUTINE (R62)","notes":""},
						 {"number":50,"description":"PLEASE PERFORM","notes":""},
						 {"number":51,"description":"","notes":""},
						 {"number":52,"description":"MARK X-RETICLE","notes":""},
						 {"number":53,"description":"MARK Y-RETICLE","notes":""},
						 {"number":54,"description":"MARK X OR Y-RETICLE","notes":""},
						 {"number":55,"description":"INCREMENT AGC TIME (DECIMAL)","notes":""},
						 {"number":56,"description":"TERMINATE TRACKING (P20 + P25)","notes":""},
						 {"number":57,"description":"PERMIT LANDING RADAR UPDATES","notes":""},
						 {"number":58,"description":"INHIBIT LANDING RADAR UPDATES","notes":""},
						 {"number":59,"description":"COMMAND LR TO POSITON 2.","notes":""},
						 {"number":60,"description":"DISPLAY VEHICLE ATTITUDE RATES ON FDAI ERROR NEEDLES.","notes":""},
						 {"number":61,"description":"DISPLAY DAP FOLLOWING ATTITUDE ERRORS.","notes":""},
						 {"number":62,"description":"DISPLAY TOTAL ATTITUDE ERRORS WITH RESPECT TO NOUN 22.","notes":""},
						 {"number":63,"description":"SAMPLE RADAR ONCE PER SECOND (R04).","notes":""},
						 {"number":64,"description":"REQUEST S-BAND ANTENNA ROUTINE (R05).","notes":""},
						 {"number":65,"description":"DISABLE U AND V JET FIRINGS DURING DPS BURNS.","notes":""},
						 {"number":66,"description":"VEHICLES ARE ATTACHED.MOVE THIS VEHICLE STATE TO OTHER VEHICLE.","notes":""},
						 {"number":67,"description":"DISPLAY W MATRIX","notes":""},
						 {"number":68,"description":"","notes":""},
						 {"number":69,"description":"CAUSE RESTART","notes":""},
						 {"number":70,"description":"UPDATE LIFTOFF TIME","notes":""},
						 {"number":71,"description":"UNIVERSAL UPDATE-BLOCK ADR","notes":""},
						 {"number":72,"description":"UNIVERSAL UPDATE-SINGLE ADR","notes":""},
						 {"number":73,"description":"UPDATE AGC TIME (OCTAL)","notes":""},
						 {"number":74,"description":"INITIALIZE ERASABLE DUMP VIA DOWNLINK","notes":""},
						 {"number":75,"description":"ENABLE U AND V JET FIRINGS DURING DPS BURNS.","notes":""},
						 {"number":76,"description":"MINIMUM IMPUSE COMMAND MODE.","notes":""},
						 {"number":77,"description":"RATE COMMAND AND ATTITUDE HOLD MODE","notes":""},
						 {"number":78,"description":"LR SPURIOUS RETURN TEST START (R77)","notes":""},
						 {"number":79,"description":"LR SPURIOUS RETURN TEST STOP","notes":""},
						 {"number":80,"description":"UPDATE LEM STATE VECTOR","notes":""},
						 {"number":81,"description":"UPDATE CSM STATE VECTOR","notes":""},
						 {"number":82,"description":"REQUEST ORBIT PARAM DISPLAY (R30)","notes":""},
						 {"number":83,"description":"REQUEST REND PARAM DISPLAY (R31)","notes":""},
						 {"number":84,"description":"","notes":""},
						 {"number":85,"description":"DISPLAY RR LOS AZ AND ELEV","notes":""},
						 {"number":86,"description":"","notes":""},
						 {"number":87,"description":"","notes":""},
						 {"number":88,"description":"","notes":""},
						 {"number":89,"description":"REQUEST RENDEZVOUS FINAL ATTITUDE ROUTINE (R63)","notes":""},
						 {"number":90,"description":"REQUEST RENDEZVOUS OUT OF PLANE DISPLAY ROUTINE (R36)","notes":""},
						 {"number":91,"description":"DISPLAY BANK SUM","notes":""},
						 {"number":92,"description":"OPERATE IMU PERFORMANCE TEST (P07)","notes":""},
						 {"number":93,"description":"ENABLE W MATRIX INITALIZATION","notes":""},
						 {"number":94,"description":"","notes":""},
						 {"number":95,"description":"NO UPDATE OF EITHER STATE VECTOR (P20 OR P22)","notes":""},
						 {"number":96,"description":"INTERRUPT INTEGRATION AND GO TO P00","notes":""},
						 {"number":97,"description":"PERFORM ENGINE FAIL PROCEDURE","notes":""},
						 {"number":98,"description":"","notes":""},
						 {"number":99,"description":"PLEASE ENABLE ENGINE","notes":""}
				 ],
		"nouns" :
				 [
						 {"number":0,"description":"NOT IN USE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":1,"description":"SPECIFY MACHINE ADDRESS (FRACTIONAL)","components":"3COMP","scale":".xxxxx FOR EACH","notes_org":"","notes":""},
						 {"number":2,"description":"SPECIFY MACHINE ADDRESS (WHOLE)","components":"3COMP","scale":"xxxxx. FOR EACH","notes_org":"","notes":""},
						 {"number":3,"description":"SPECIFY MACHINE ADDRESS (DEGREES)","components":"3COMP","scale":"xxx.xx DEG FOR EACH","notes_org":"","notes":""},
						 {"number":4,"description":"ANGULAR ERROR/DIFFERENCE","components":"1COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":5,"description":"ANGULAR ERROR/DIFFERENCE","components":"1COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":6,"description":"OPTION CODE","components":"3COMP","scale":"","notes_org":"OCTAL ONLY","notes":""},
						 {"number":7,"description":"ECADR OF WORD TO BE MODIFIED","components":"3COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":8,"description":"ALARM DATA","components":"3COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":9,"description":"ALARM CODES","components":"3COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":10,"description":"CHANNEL TO BE SPECIFIED","components":"1COMP","scale":"","notes_org":"OCTAL ONLY","notes":""},
						 {"number":11,"description":"TIG OF CSI","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":12,"description":"OPTION CODE","components":"2COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":13,"description":"TIG OF CDH","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":14,"description":"CHECKLIST","components":"3COMP","scale":"xxxxx. FOR EACH","notes_org":"","notes":""},
						 {"number":15,"description":"INCREMENT MACHINE ADDRESS","components":"1COMP","scale":"","notes_org":"OCTAL ONLY","notes":""},
						 {"number":16,"description":"TIME OF EVENT","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":17,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":18,"description":"AUTO MANEUVER BALL ANGLES","components":"3COMP","scale":"xxx.xx DEG FOR EACH","notes_org":"","notes":""},
						 {"number":19,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":20,"description":"ICDU ANGLES","components":"3COMP","scale":"xxx.xx DEG FOR EACH","notes_org":"","notes":""},
						 {"number":21,"description":"PIPAS","components":"3COMP","scale":"xxxxx. PULSES FOR EACH","notes_org":"","notes":""},
						{"number":22,"description":"NEW ICDU ANGLES","components":"3COMP","scale":"xxx.xx DEG FOR EACH","notes_org":"","notes":""},
						 {"number":23,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":24,"description":"DELTA TIME FOR AGC CLOCK","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":25,"description":"CHECKLIST","components":"3COMP","scale":"xxxxx. FOR EACH","notes_org":"","notes":""},
						 {"number":26,"description":"PRIORITY/DELAY, ADRES, BBCON","components":"3COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":27,"description":"SELF TEST ON/OFF SWITCH","components":"1COMP","scale":"xxxxx.","notes_org":"","notes":""},
						 {"number":28,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":29,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":30,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":31,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":32,"description":"TIME FROM PERIGEE","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":33,"description":"TIME OF IGNITION","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":34,"description":"TIME OF EVENT","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":35,"description":"TIME FROM EVENT","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":36,"description":"TIME OF AGC CLOCK","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":37,"description":"TIG OF TPI","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						 {"number":38,"description":"TIME OF STATE BEING INTEGRATED","components":"3COMP","scale":"00xxx. HRS","notes_org":"DEC ONLY","notes":""},
						{"number":39,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":40,"description":"TIME FROM IGNITION/CUTOFF","components":"3COMP","scale":"xxBxx MIN/SEC","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":41,"description":"TARGET AXIMUTH","components":"2COMP","scale":"xxx.xx DEG","notes_org":"(FOR SYSTEM TEST)","notes":""},
						 {"number":42,"description":"APOGEE,","components":"3COMP","scale":"xxxx.x NAUT MI","notes_org":"DEC ONLY","notes":""},
						 {"number":43,"description":"LATITUDE,","components":"3COMP","scale":"xxx.xx DEG","notes_org":"DEC ONLY","notes":""},
						 {"number":44,"description":"APOGEE,","components":"3COMP","scale":"xxxx.x NAUT MI","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":45,"description":"MARKS,","components":"3COMP","scale":"xxxxx.","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":46,"description":"AUTOPILOT CONFIGURATION","components":"1COMP","scale":"","notes_org":"OCTAL ONLY","notes":""},
						 {"number":47,"description":"LEM WEIGHT,","components":"2COMP","scale":"xxxxx. LBS","notes_org":"DEC ONLY","notes":""},
						 {"number":48,"description":"GIMBAL PITCH TRIM,","components":"2COMP","scale":"xxx.xx DEG","notes_org":"DEC ONLY","notes":""},
						 {"number":49,"description":"DELTA R,","components":"3COMP","scale":"xxxx.x NAUT MI","notes_org":"DEC ONLY","notes":""},
						 {"number":50,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":51,"description":"S-BAND ANTENNA ANGLESPITCH","components":"2COMP","scale":"xxx.xx DEG","notes_org":"DEC ONLY","notes":""},
						 {"number":52,"description":"CENTRAL ANGLE OF ACTIVE VEHICLE","components":"1COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":53,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":54,"description":"RANGE,","components":"3COMP","scale":"xxx.xx NAUT MI","notes_org":"DEC ONLY","notes":""},
						 {"number":55,"description":"NO. OF APSIDAL CROSSINGS","components":"3COMP","scale":"xxxxx.","notes_org":"DEC ONLY","notes":""},
						 {"number":56,"description":"RR LOS AZIMUTH","components":"2COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":57,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":58,"description":"PERIGEE ALT (POST TPI)","components":"3COMP","scale":"xxxx.x NAUT MI","notes_org":"DEC ONLY","notes":""},
						 {"number":59,"description":"DELTA VELOCITY LOS","components":"3COMP","scale":"xxxx.x FT/SEC FOR EA.","notes_org":"DEC ONLY","notes":""},
						 {"number":60,"description":"FORWARD VELOCITY","components":"3COMP","scale":"xxxx.x FT/SEC","notes_org":"DEC ONLY","notes":""},
						 {"number":61,"description":"TIME TO GO IN BRAKING PHASE","components":"3COMP","scale":"xxBxx MIN/SEC","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":62,"description":"ABSOLUTE VALUE OF VELOCITY","components":"3COMP","scale":"xxxx.x FT/SEC","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":63,"description":"ABSOLUTE VALUE OF VELOCITY","components":"3COMP","scale":"xxxx.x FT/SEC","notes_org":"DEC ONLY","notes":""},
						 {"number":64,"description":"TIME LEFT FOR REDESIGNATION--LPD ANGLE","components":"3COMP","scale":"xxBxx","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":65,"description":"SAMPLED AGC TIME","components":"3COMP","scale":"00xxx. HRS.","notes_org":"DEC ONLY","notes":""},
						 {"number":66,"description":"LRRANGE","components":"2COMP","scale":"xxxxx. FEET","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":67,"description":"LRVX","components":"3COMP","scale":"xxxxx. FT/SEC","notes_org":"","notes":""},
						 {"number":68,"description":"SLANT RANGE TO LANDING SITE","components":"3COMP","scale":"xxxx.x NAUT MI","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":69,"description":"LANDING SITE CORRECTION, Z-COMPONENT","components":"3COMP","scale":"xxxxx. FEET","notes_org":"DEC ONLY","notes":""},
						 {"number":70,"description":"AOT DETENT CODE/STAR CODE","components":"3COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":71,"description":"AOT DETENT CODE/STAR CODE","components":"3COMP","scale":"","notes_org":"OCTAL ONLY FOR EACH","notes":""},
						 {"number":72,"description":"RR 360 -- TRUNNION ANGLE","components":"2COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":73,"description":"NEW RR 360 -- TRUNNION ANGLE","components":"2COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":74,"description":"TIME FROM IGNITION","components":"3COMP","scale":"xxBxx MIN/SEC","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":75,"description":"DELTA ALTITUDE CDH","components":"3COMP","scale":"xxxx.x NAUT MI","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":76,"description":"DESIRED HORIZONTAL VELOCITY","components":"3COMP","scale":"xxxx.x FT/SEC","notes_org":"DEC ONLY","notes":""},
						 {"number":77,"description":"TIME TO ENGINE CUTOFF","components":"2COMP","scale":"xxBxx MIN/SEC","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":78,"description":"RR RANGE","components":"3COMP","scale":"xxx.xx NAUT MI","notes_org":"NO LOAD, DEC ONLY","notes":""},
						 {"number":79,"description":"CURSOR ANGLE","components":"3COMP","scale":"xxx.xx DEG","notes_org":"DEC ONLY","notes":""},
						 {"number":80,"description":"DATA INDICATOR,","components":"2COMP","scale":"xxxxx.","notes_org":"","notes":""},
						 {"number":81,"description":"DELTA V (LV)","components":"3COMP","scale":"xxxx.x FT/SEC FOR EACH ","notes_org":"DEC ONLY","notes":""},
						 {"number":82,"description":"DELTA V (LV)","components":"3COMP","scale":"xxxx.x FT/SEC FOR EACH","notes_org":"DEC ONLY","notes":""},
						 {"number":83,"description":"DELTA V (BODY)","components":"3COMP","scale":"xxxx.x FT/SEC FOR EACH","notes_org":"DEC ONLY","notes":""},
						 {"number":84,"description":"DELTA V (OTHER VEHICLE)","components":"3COMP","scale":"xxxx.x FT/SEC FOR EACH","notes_org":"DEC ONLY","notes":""},
						 {"number":85,"description":"VG (BODY)","components":"3COMP","scale":"xxxx.x FT/SEC FOR EACH","notes_org":"DEC ONLY","notes":""},
						 {"number":86,"description":"VG (LV)","components":"3COMP","scale":"xxxx.x FT/SEC FOR EACH","notes_org":"DEC ONLY","notes":""},
						 {"number":87,"description":"BACKUP OPTICS LOS AZIMUTH","components":"2COMP","scale":"xxx.xx DEG","notes_org":"","notes":""},
						 {"number":88,"description":"HALF UNIT SUN OR PLANET VECTOR","components":"3COMP","scale":".xxxxx FOR EACH","notes_org":"DEC ONLY","notes":""},
						 {"number":89,"description":"LANDMARK LATITUDE","components":"3COMP","scale":"xx.xxx DEG","notes_org":"DEC ONLY","notes":""},
						 {"number":90,"description":"y","components":"3COMP","scale":"xxx.xx NM","notes_org":"DEC ONLY","notes":""},
						 {"number":91,"description":"ALTITUDE","components":"3COMP","scale":"xxxxxB. NAUT MI","notes_org":"","notes":""},
						 {"number":92,"description":"PCT FTP (10.5K LB) AT PRESENT THRUST","components":"3COMP","scale":"xxxxx.","notes_org":"","notes":""},
						 {"number":93,"description":"DELTA GYRO ANGLES","components":"3COMP","scale":"xx.xxx DEG FOR EACH","notes_org":"","notes":""},
						 {"number":94,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":95,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":96,"description":"SPARE","components":"","scale":"","notes_org":"","notes":""},
						 {"number":97,"description":"SYSTEM TEST INPUTS","components":"3COMP","scale":"xxxxx. FOR EACH","notes_org":"","notes":""},
						 {"number":98,"description":"SYSTEM TEST RESULTS AND INPUTS","components":"3COMP","scale":"xxxxx.","notes_org":"","notes":""},
						 {"number":99,"description":"RMS IN POSITION","components":"3COMP","scale":"xxxxx. FT","notes_org":"DEC ONLY","notes":""}
				],
		"progs" : []
}